### ISSUE TITLE
Regen Mod is not loaded with SMAPI 2.6-beta.14 + SDV 1.3.11, here's the error if loading is forced :

### ISSUE THREAD

**Issue by HorusLupercal** [Zoryn4163/SMAPI-Mods#14]
Default behavior is not loading the mod at all.
If forced by writing "Status:AssumeCompatible" in StardewModdingAPI.metadata.json the following error code appears and repeats ad infinitum in the SMAPI console :

13:58:33 | ERROR | Regen Mod | This mod failed in the GameEvents.UpdateTick event. Technical details:  System.MissingFieldException: Field not found : 'StardewValley.Farmer.maxStamina'.
at RegenMod.ModEntry.GameEvents_UpdateTick(Object sender, EventArgs e)
at StardewModdingAPI.Framework.Events.ManagedEvent.Raise()
in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 110

Hopefully it helps

**Comment by HorusLupercal** [comment]
The following changelog is the updates from SDV 1.3.11, they apparently fixed something related to stamina loss if that's any help :
![image](https://user-images.githubusercontent.com/39458929/40278822-9fc54748-5c38-11e8-9af0-02c8cd6aed27.png)

**Comment by climber59** [comment]
I'm getting the same issue. Just downloaded Regen 1.9 from the release page today.
