### ISSUE TITLE
"FishingMod.dll" doesn't exist?

### ISSUE THREAD

**Issue by muyangwu** [Zoryn4163/SMAPI-Mods#16]
I got an error in terminal says "[SMAPI] Skipped 1 mods:
[SMAPI]    Fishing Mod 1.9 because its DLL 'FishingMod.dll' doesn't exist." Should I just copy the dll file and paste it in the folder?

**Comment by Pathoschild** [comment]
It sounds like you installed it incorrectly or an antivirus is deleting the DLL. Make sure all the mod files from the download are present.
