### ISSUE TITLE
fishing mod

### ISSUE THREAD

**Issue by ashleyyjixx** [Zoryn4163/SMAPI-Mods#17]
i installed this ran the game played for a day save my progress and the conf.json never showed

**Comment by Pathoschild** [comment]
Can you [upload your SMAPI log](https://log.smapi.io) (see instructions on that page) and post a link here?

**Comment by ashleyyjixx** [comment]
i did but since i didnt see this message i already updated smapi so that error log isnt there anymore sorry


-----Original Message-----

**Comment by Pathoschild** [comment]
That's fine. If it's still happening, can you upload a new log and post it here?
