### ISSUE TITLE
Tackle Degrades With Fishing Mod

### ISSUE THREAD

**Issue by MoralTruth** [Zoryn4163/SMAPI-Mods#18]
Hello there. With the Fishing Mod, my tackles lose durability when I’m fishing, then degrade. Unlimited bait is working fine, but not unlimited tackles. Tackles also refresh their durability when swapping to them, which is quite odd.

**Comment by MoralTruth** [comment]
Any reason why this was closed? I can go more into detail with my issue or answer any questions to better understand the issue if needed.

**Comment by Zoryn4163** [comment]
See 1790a6df4b2b43b1aada7072c32a8e1f03287cb4

**Comment by MoralTruth** [comment]
Thanks.
