### ISSUE TITLE
Regen mod Xinput bug?

### ISSUE THREAD

**Issue by ryutoshirazen** [Zoryn4163/SMAPI-Mods#20]
Upon testing I have noticed an issue with the regen mod.
My settings are as such.(Temporary settings for testing)
{
  "RegenStaminaConstant": false,
  "RegenStaminaConstantAmountPerSecond": 0.0,
  "RegenStaminaStill": true,
  "RegenStaminaStillAmountPerSecond": 1.0,
  "RegenStaminaStillTimeRequiredMS": 7000,
  "RegenHealthConstant": false,
  "RegenHealthConstantAmountPerSecond": 0.0,
  "RegenHealthStill": false,
  "RegenHealthStillAmountPerSecond": 0.0,
  "RegenHealthStillTimeRequiredMS": 1000
}

When using WASD stamina does not begin to regen until 7 seconds have elapsed; however, when using a controller regen does not take movement into account and refills regardless of movement.
I verified this by using PyTK mod through smapi console getstamina command before and after moving with wasd as well as before and after moving with an Xbox controller.

I'm going to assume that regen health acts the same way.

**Comment by Zoryn4163** [comment]
Commit https://github.com/Zoryn4163/SMAPI-Mods/commit/76abeb429534208de728814b493877bde04b0360 should fix this. I don't have a controller to verify
