### ISSUE TITLE
DDL file for Decaying Fences Mod?

### ISSUE THREAD

**Issue by ZDT534459** [Zoryn4163/SMAPI-Mods#21]
I'm grateful to of found someone who could update so many variety of mods which I use during the big update, but I found an issue with your Decaying Fences Mod. Whenever I boot up the game the command prompt tells me that specific mod is missing its DDL file. And thus the mod is skipped. Never worked with a DDL file, so, here's hoping you see this.

**Comment by Pathoschild** [comment]
If you're still having trouble, come ask in [#modding on the Stardew Valley Discord](https://smapi.io/community#Discord) and we'll help!
