### ISSUE TITLE
Click area doesn't handle zoom correctly

### ISSUE THREAD

**Issue by Drexl** [Zoryn4163/SMAPI-Mods#22]
Given I use a lot of mods I tried using this mod by itself. Nothing happens. When placing my cursor over the date it doesn't change, and clicking it does nothing.

**Comment by Drexl** [comment]
BillboardAnywhere seems to work fine so I'm using that for now, but I'd like to use this one in the future.

**Comment by Pathoschild** [comment]
The text doesn't change to 'calendar' for me, but clicking the date does open the menu. Can you [upload your SMAPI log](https://log.smapi.io) (see instructions on that page) and post a link here?

**Comment by Drexl** [comment]
https://log.smapi.io/w7iBLkez

**Comment by Pathoschild** [comment]
* Are you using a mouse or controller to click? 
* Just to make sure, are you clicking here?  
   ![](https://user-images.githubusercontent.com/230581/54065901-0d73da00-41f5-11e9-85a8-23990097f873.png)
* What is your zoom level set to in the game options?

**Comment by Drexl** [comment]
I'm using a mouse, and yes that's where I'm clicking. I can't blame you for checking though. :D
I also tried clicking everywhere around it. My zoom level is 85%. I can take a video if you'd like.

**Comment by Pathoschild** [comment]
Seems to be a zoom-related miscalculation in the mod code:

zoom level | click area
---------- | ----------
95% | ![image](https://user-images.githubusercontent.com/230581/54066655-d35d0500-4201-11e9-93b2-f6b4d320ef6b.png)
100% | ![](https://user-images.githubusercontent.com/230581/54066632-46b24700-4201-11e9-9049-f530ae082663.png)
105% | ![](https://user-images.githubusercontent.com/230581/54066642-9abd2b80-4201-11e9-8954-6a6a6bfb855a.png)

**Comment by xuqingxin001** [comment]
This bug is not fixed? I am 75% zoom 2.6 no problem

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming Calendar Anywhere 2.7.3.
