### ISSUE TITLE
Slime Hutch Health Bars

### ISSUE THREAD

**Issue by MacApple777** [Zoryn4163/SMAPI-Mods#25]
Hi Zoryn,

I don't know if this is possible, but is there a way to have the mod disable health bars in the Slime Hutch? The bars interact weirdly with the inventory screen. I have a mod that gives me more slime capacity, but often they manage to damage themselves even at the normal limit. There's no good way to kill a single slime so it's usually all or nothing if I want to clear them out.

![Screenshot (45)](https://user-images.githubusercontent.com/80149384/110200490-4ec31280-7e2c-11eb-9d9e-ff8fec1be081.png)
![Screenshot (46)](https://user-images.githubusercontent.com/80149384/110200492-4ff43f80-7e2c-11eb-80d0-5335e694e82b.png)

**Comment by Pathoschild** [comment]
Fixed in the upcoming Health Bars 2.8.1, which won't draw health bars over the menu anymore. Thanks for reporting it!
