### ISSUE TITLE
HealthBars misaligned when zoom level != ui scale

### ISSUE THREAD

**Issue by MrMagoozor** [Zoryn4163/SMAPI-Mods#27]
HealthBars are misaligned when the "Zoom Level" is different than the "UI Scale" option. 

![Screenshot 2022-01-18 120112](https://user-images.githubusercontent.com/17347275/149962484-580de443-423c-4169-9548-9e7b71e3e402.png)

This is With 100% UI scale but 75% Zoom Level.

**Comment by Pathoschild** [comment]
Fixed via #28. Thanks for reporting it!
