### ISSUE TITLE
Request: Horse Movement

### ISSUE THREAD

**Issue by SuperiorS69** [Zoryn4163/SMAPI-Mods#3]
I'm not sure if you can but Horse Speed Modifer would be an awesome inclusion to the movement modifier because currently at the default config you run almost as fast as the horse. Just a suggestion.

**Comment by Zoryn4163** [comment]
I don't actually have a horse, do you know if your speed is increased by the mod when on the horse?

**Comment by SuperiorS69** [comment]
I'm not sure my save broke in the switch from Storm to SMAPI and I hadn't backed up before. So had to restart. In Storm if I remember correctly the movement modifier didn't affect the horse.

**Comment by Zoryn4163** [comment]
Okay. I'm done with developing for tonight, but I can look into it tomorrow. (EST)
Edit: That is very strange though, your save should not have broken. I moved over to SMAPI without any issues :/

**Comment by SuperiorS69** [comment]
Alright cool, yeah it's hard telling what I did, didn't lose much progress and much prefer SMAPI so far.

**Comment by SuperiorS69** [comment]
Nvm got a horse movement modifier effects speed I'll let you close this so you know its not an issue.

**Comment by Zoryn4163** [comment]
I intend to implement this as an additional config value, don't close it :)

**Comment by Zoryn4163** [comment]
Added as of 6c8681ad8afdbe1f99ba6de0bc6265a68e463272
Should work.
Release will be coming soon.
