### ISSUE TITLE
Request: Regen Mod

### ISSUE THREAD

**Issue by timroham** [Zoryn4163/SMAPI-Mods#4]
How hard is it to add the ability to have two separate regen settings for stamina? One slow regen for when the player is active, one quicker regen when the character is standing still. I'm currently achieving the same effect running two separate regen mods (yours + StaminaRegen by natfoth/evilpdor.) but I would like to have that in a single mod. Updates by other people can be... problematic... at times.

**Comment by Zoryn4163** [comment]
I'll do that when I fix some problems in my other mods. It's quite easy

**Comment by Zoryn4163** [comment]
Implemented in ccc73e88d9f5c34d0063eb9e5de342b3e52abc71
It will be available in the next release build (soon)
Prior configs will not be compatible and will be cleared.
