### ISSUE TITLE
JunimoDepositAnywhere Mod

### ISSUE THREAD

**Issue by ghost** [Zoryn4163/SMAPI-Mods#5]
If anything is deposited into the community center that completes a bundle using the JumimoDepositAnywhere mod, the game will crash the next time the player sleeps and saves the game. 

Other Mods Used: 
CalendarAnywhere
FishingMod
HealthBars
NPCMapLocations
SMAPIChestLabelSystem
StardewCJB
TrainerMod

API Console Output
![image](https://cloud.githubusercontent.com/assets/18524025/14594834/63f948ee-04f7-11e6-88a1-ffc530205dd5.png)

Thanks for the great mods, just thought it would be helpful to give input on these, keep up the good work.

**Comment by Zoryn4163** [comment]
Hi, please read the following statement that is in my OP of my mods' forum thread:
- Junimo Deposit Anywhere:
  - **WARNING: If this is not used in a very specific way, your game will crash. You will lose all progress for the day you were on. I will not help you if you do not read the following warning: Completing a bundle outside of the community center will invariably crash your game. I have used this mod constantly without a crash occurring. When depositing an item into the box-things, I would advise right-clicking to pick up the item, and left clicking to place it down, as this does actually make a difference code-wise, but again, do not complete a bundle outside of the community center. That is all.**
  -  Deposit any item to the Junimo bundles from anywhere from the Bundles menu.

I do apologize for this bug, but it is not within my ability to fix it at this moment, and the current "solution" is to not complete a bundle outside of the building, sorry.

**Comment by ghost** [comment]
It's fine, and thank you for the quick response, I was merely directed to your github page, not through the post, so I appreciate the input, and was unaware of the issue.  Sorry about wasting your time, and again, thanks for the great mods.

**Comment by Zoryn4163** [comment]
No prob, and it's fine. I added a link to my thread in the readme of git for future things like this. I do want to fix this, but I'm busy currently.  Perhaps over the summer I will be able to as I work significantly less and should have more time. Thanks for the appreciation though, it still means a lot to me.
